/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lxm_ss_test_MyJni */

#ifndef _Included_com_lxm_ss_test_MyJni
#define _Included_com_lxm_ss_test_MyJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lxm_ss_test_MyJni
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lxm_ss_test_MyJni_sayHello
  (JNIEnv *env, jclass jobj){
    //返回一句话
    return (*env)->NewStringUTF(env,"JNI hahahahahahahaha");
}

#ifdef __cplusplus
}
#endif
#endif
