//
// Created by lxm on 2017/8/28.
//

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lxm_ss_test_MyJni */

#ifndef _Included_com_lxm_ss_test_MyJni
#define _Included_com_lxm_ss_test_MyJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lxm_ss_test_MyJni
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
 //就实现了个函数 JNIEnv的用法可以自行百度，这里就不展开了
JNIEXPORT jstring JNICALL Java_com_lxm_ss_test_MyJni_sayHello
        (JNIEnv *env, jclass jobj){

    //返回一句话
    return (*env)->NewStringUTF(env,"JNI hahahahahahahaha");

    }

#ifdef __cplusplus
}
#endif
#endif
